--- src/makefile.orig	2015-07-29 16:31:15.235604603 +0200
+++ src/makefile	2015-07-29 16:32:12.232602501 +0200
@@ -25,8 +25,8 @@
 PROGRAMS	=	../bin/analyseplugin				\
 			../bin/applyplugin 				\
 			../bin/listplugins
-CC		=	cc
-CPP		=	c++
+#CC		=	cc
+#CPP		=	c++
 
 ###############################################################################
 #
@@ -35,11 +35,12 @@
 
 ../plugins/%.so:	plugins/%.c ladspa.h
 	$(CC) $(CFLAGS) -o plugins/$*.o -c plugins/$*.c
-	$(LD) -o ../plugins/$*.so plugins/$*.o -shared
+	$(CC) -o ../plugins/$*.so plugins/$*.o -shared $(CFLAGS) $(LDFLAGS)
 
 ../plugins/%.so:	plugins/%.cpp ladspa.h
 	$(CPP) $(CXXFLAGS) -o plugins/$*.o -c plugins/$*.cpp
-	$(CPP) -o ../plugins/$*.so plugins/$*.o -shared
+	$(CPP) -o ../plugins/$*.so plugins/$*.o -shared $(CXXFLAGS) $(LDFLAGS)
+	echo $(LDFLAGS)
 
 ###############################################################################
 #
@@ -59,9 +59,12 @@
 	@echo Test complete.
 
 install:	targets
-	-mkdirhier $(INSTALL_PLUGINS_DIR)
-	-mkdirhier $(INSTALL_INCLUDE_DIR)
-	-mkdirhier $(INSTALL_BINARY_DIR)
+#	-mkdirhier $(INSTALL_PLUGINS_DIR)
+#	-mkdirhier $(INSTALL_INCLUDE_DIR)
+#	-mkdirhier $(INSTALL_BINARY_DIR)
+	mkdir -p $(INSTALL_PLUGINS_DIR)
+	mkdir -p $(INSTALL_INCLUDE_DIR)
+	mkdir -p $(INSTALL_BINARY_DIR)
 	cp ../plugins/* $(INSTALL_PLUGINS_DIR)
 	cp ladspa.h $(INSTALL_INCLUDE_DIR)
 	cp ../bin/* $(INSTALL_BINARY_DIR)
